from anyio import current_time
from matplotlib.pyplot import table
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors 
from reportlab.pdfbase.pdfmetrics import registerFont
from reportlab.pdfbase.ttfonts import TTFont
import io
from datetime import datetime
import random
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
import re




try:
    registerFont(TTFont("Helvetica", "Helvetica.ttf"))
except:
    pass

def extract_iocs(parsed_logs):

    ips = set()
    users = set()
    services = set()
    hosts = set()

    failed_logins = 0

    for _, row in parsed_logs.iterrows():

        message = str(row["message"])

        hosts.add(str(row["host"]))
        services.add(str(row["service"]))

        ip_matches = re.findall(
            r"\b(?:\d{1,3}\.){3}\d{1,3}\b",
            message
        )

        ips.update(ip_matches)

        user_matches = re.findall(
            r"user=([A-Za-z0-9_-]+)",
            message
        )

        users.update(user_matches)

        if "authentication failure" in message.lower():
            failed_logins += 1

    return {

        "ips": sorted(list(ips)),

        "users": sorted(list(users)),

        "services": sorted(list(services)),

        "hosts": sorted(list(hosts)),

        "failed": failed_logins

    }
def create_incident_pdf(report,parsed_logs):

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
    buffer,
    pagesize=A4,
    rightMargin=40,
    leftMargin=40,
    topMargin=40,
    bottomMargin=40)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = colors.darkblue

    heading_style = styles["Heading2"]

    normal = styles["BodyText"]

    story = []
    ioc = extract_iocs(parsed_logs)

    story.append(Paragraph("<font size=24><b>AI LOG ANALYZER</b></font>",title_style))

    story.append(Spacer(1,15))

    story.append(
    Paragraph(
        "<font size=18><b>Cybersecurity Incident Report</b></font>",
        title_style
        )
    )

    story.append(Spacer(1,30))
    #current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    table_data = [
        ["Generated On", datetime.now()],
        ["Generated By", "AI Log Analyzer"]
        ]

    table = Table(table_data, colWidths=[160,250])

    table.setStyle(TableStyle([
    ("BACKGROUND",(0,0),(0,-1),colors.darkblue),
    ("TEXTCOLOR",(0,0),(0,-1),colors.white),

    ("BACKGROUND",(1,0),(1,-1),colors.beige),

    ("GRID",(0,0),(-1,-1),1,colors.grey),

    ("FONTNAME",(0,0),(-1,-1),"Helvetica-Bold"),

    ("BOTTOMPADDING",(0,0),(-1,-1),10),

    ("TOPPADDING",(0,0),(-1,-1),10),

    ("ALIGN",(0,0),(-1,-1),"CENTER")
    ]))

    story.append(table)

    story.append(Spacer(1,40))

    story.append(
        Paragraph(
            "Incident Report",
            heading_style
        )
    )

    story.append(Spacer(1, 10))

    for line in report.split("\n"):

        if line.strip() == "":
            continue

        story.append(Paragraph(line, normal))
    story.append(Spacer(1,20))

    story.append(
    Paragraph(
        "<b>Indicators of Compromise (IOC)</b>",
        heading_style
    )
)
    styles = getSampleStyleSheet()
    body_style = styles["BodyText"]
    story.append(Paragraph("<b>Indicators of Compromise (IOC Summary)</b>", heading_style))
    story.append(Spacer(1, 10))

    ioc_data = [
    ["IOC Type", "Count"],
    ["Source IPs", str(len(ioc["ips"]))],
    ["Usernames", str(len(ioc["users"]))],
    ["Services", str(len(ioc["services"]))],
    ["Hostnames", str(len(ioc["hosts"]))],
    ["Failed Logins", str(ioc["failed"])]
    ]

    ioc_table = Table(ioc_data, colWidths=[220,100])

    ioc_table.setStyle(TableStyle([
    ("BACKGROUND",(0,0),(-1,0),colors.darkblue),
    ("TEXTCOLOR",(0,0),(-1,0),colors.white),
    ("GRID",(0,0),(-1,-1),1,colors.grey),
    ("BACKGROUND",(0,1),(0,-1),colors.beige),
    ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
    ("FONTNAME",(0,1),(-1,-1),"Helvetica"),
    ("ALIGN",(0,0),(-1,-1),"CENTER"),
    ("BOTTOMPADDING",(0,0),(-1,0),8),
]))


    story.append(ioc_table)
    story.append(Spacer(1,20))
    

    doc.build(story)

    buffer.seek(0)

    return buffer