from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import darkblue
from reportlab.pdfbase.pdfmetrics import registerFont
from reportlab.pdfbase.ttfonts import TTFont
import io
from datetime import datetime
import random

try:
    registerFont(TTFont("Helvetica", "Helvetica.ttf"))
except:
    pass


def create_incident_pdf(report):

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = darkblue

    heading_style = styles["Heading2"]

    normal = styles["BodyText"]

    story = []

    story.append(
        Paragraph(
            "CYBERSECURITY INCIDENT REPORT",
            title_style
        )
    )

    story.append(Spacer(1, 20))

    incident_id = f"INC-{random.randint(1000,9999)}"

    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    story.append(
        Paragraph(
            f"<b>Incident ID:</b> {incident_id}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Generated:</b> {current_time}",
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>Generated By:</b> AI Log Analyzer",
            normal
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Incident Report",
            heading_style
        )
    )

    story.append(Spacer(1, 10))

    for line in report.split("\n"):

        if line.strip() == "":
            continue

        story.append(
            Paragraph(line, normal)
        )

    doc.build(story)

    buffer.seek(0)

    return buffer